---
- name: name playbook
  hosts: all
  become: yes

  vars:
    wp_db_name : "mydb"
    wp_db_user : "admin"
    wp_db_pass : "admin"
    site_name  : "/var/www/mysite"

  roles:
    - setup_mysql
    - setup_nginx
    - setup_wordpress
