---
- name: name playbook
  hosts: all
  become: yes

  tasks:
    - name: Install MySQL
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - 'mysql-server'
        - 'mysql-client'
        - 'python3-mysqldb'
        - 'python3-pymysql'
        - 'libmysqlclient-dev'
      notify: config mysql - set MySQL root password

    - name: Config MySQL - Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Config MySQL - Creates database for WordPress
      mysql_db:
        name: 'mydb'
        state: 'present'
        login_user: 'root'
        login_password: 'root'

    - name: config mysql - creates user for wordpress
      mysql_user:
        name: 'admin'
        password: 'admin'
        login_user: 'root'
        login_password: 'root'
        priv: "*.*:ALL"

  roles:
    - setup_nginx
    - setup_wordpress

  handlers:
    - name: config mysql - set MySQL root password
      mysql_user:
        name: "root"
        password: 'root'
        login_unix_socket: /var/run/mysqld/mysqld.sock
