---
# tasks file for setup_nginx
- name: Install Nginx and php
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - 'nginx'
    - 'php'
    - 'php-fpm'
    - 'php-mysql'

- name: Config Nginx - upload my config file
  copy:
    src: my_config
    dest: /etc/nginx/sites-available

- name: Config Nginx - symbolic link to my nginx config file
  file:
    state: link
    src: "/etc/nginx/sites-available/my_config"
    path: "/etc/nginx/sites-enabled/default"

- name: Config Nginx - creat /var/www/site_name folder
  command:
    cmd: "mkdir {{ site_name }}"
    creates: "{{ site_name }}"

- name: Config Nginx - Delete nginx default page
  command:
    cmd: 'rm -rf /var/www/html'

- name: Config Nginx - Start service
  service:
    name: nginx
    state: started
    enabled: yes
