---
# tasks file for setup_mysql
- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'mysql-server'
    - 'mysql-client'
    - 'python3-pymysql'

- name: config mysql - set MySQL root password
  mysql_user:
    name: "root"
    password: "{{ db_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Config MySQL - Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Config MySQL - Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: 'present'
    login_user: 'root'
    login_password: "{{ db_pass }}"

- name: config mysql - creates user for wordpress
  mysql_user:
    name: '{{ wp_db_user }}'
    password: '{{ wp_db_pass }}'
    login_user: 'root'
    login_password: "{{ db_pass }}"
    priv: "*.*:ALL"
