---
# tasks file for setup_mysql
- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'mysql-server'
    - 'python3-mysqldb'
    - 'python3-pymysql'
  notify: config mysql - set MySQL root password

- name: Config MySQL - Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Config MySQL - Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: 'present'
    login_user: 'root'
    login_password: "{{ db_pass }}"

- name: config mysql - creates user for wordpress
  mysql_user:
    name: 'wp_db_user'
    password: 'wp_db_pass'
    login_user: 'root'
    login_password: "{{ db_pass }}"
    priv: "*.*:ALL"
