---
# tasks file for setup_wordpress
- name: Dowload and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    remote_src: yes
    dest: "/var/www/mysite"
    creates: "/var/www/mysite/wordpress"

- name: Config WordPress - Rename wp-config-sample.php to wp-config.php
  command:
    cmd: mv "/var/www/mysite/wordpress/wp-config-sample.php" "/var/www/mysite/wordpress/wp-config.php"
    creates: "/var/www/mysite/wordpress/wp-config.php"

- name: Config WordPress - Update WordPress config file
  lineinfile:
    path: "/var/www/mysite/wordpress/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', 'mydb' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', 'admin' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', 'admin' );"}

- name: Config Nginx - Start service
  service:
    name: nginx
    state: restarted
    enabled: yes
